id: I8546A805
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:48:09+00:00'
last_modified: '2022-06-08T18:15:04.313485+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1859
  title: ས་སྐྱ་ལེགས་བཤད་རྩ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F8C4:
      image_group_id: I1CZ1924
      title: Volume 1 of sa skya legs bshad rtsa 'grel
      total_pages: 338
      order: 1
      base_file: F8C4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
