id: P008075
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1859
  title: ས་སྐྱ་ལེགས་བཤད་རྩ་འགྲེལ
  author: ''
  volumes:
    632c3bb1163044bb9646e11e482017a4:
      image_group_id: I1CZ1924
      title: Volume 1 of sa skya legs bshad rtsa 'grel
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
