id: P008075
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1859
  title: ས་སྐྱ་ལེགས་བཤད་རྩ་འགྲེལ
  author: ''
  volumes:
    ba6b6d8cd36c4225a1214e2b8c44583a:
      image_group_id: I1CZ1924
      title: ''
      volume_number: 1
      total_pages: 338
ebook_metadata:
  title: ས་སྐྱ་ལེགས་བཤད་རྩ་འགྲེལ
  author: ''
  sku: P008075
  cover: cover.jpg
  layers:
  - pagination
