id: opecha:P008075
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1859
  title: ས་སྐྱ་ལེགས་བཤད་རྩ་འགྲེལ
  volume:
    632c3bb1163044bb9646e11e482017a4:
      image_group_id: I1CZ1924
      title: Volume 1 of sa skya legs bshad rtsa 'grel
      volume_number: 1
      total_pages: 338
  author: ''
ebook_metadata:
  title: ས་སྐྱ་ལེགས་བཤད་རྩ་འགྲེལ
  author: ''
  sku: P008075
  cover: cover.jpg
  layers:
  - pagination
